### ISSUE TITLE
Package 'libjpeg62-turbo' has no installation candidate on Ubuntu 20.04

### ISSUE THREAD

**Issue by Astrr** [lobe/lobe-python#13]
>astrr@Ubuntu:~$ sudo apt install -y \
>     libatlas-base-dev \
>     libopenjp2-7 \
>     libtiff5 \
>     libjpeg62-turbo
>Reading package lists... Done
>Building dependency tree
>Reading state information... Done
>Package libjpeg62-turbo is not available, but is referred to by another package.
>This may mean that the package is missing, has been obsoleted, or
>is only available from another source

E: Package 'libjpeg62-turbo' has no installation candidate

**Comment by aidenmitchell** [comment]
https://askubuntu.com/questions/921555/how-to-install-libjpeg62-turbo-on-ubuntu-16-04-2-lts-xenial

**Comment by mbeissinger** [comment]
Seems like a fine fix to install libjpeg62-dev instead, I'll try to see if it was originally libjpeg62-turbo because of the raspberry pi

**Comment by mbeissinger** [comment]
Ok confirmed on my raspberry pi 4 that libjpeg62-dev doesn't work, and that is why the -turbo was there. Will make a note in the readme about this distinction for setup on Ubuntu vs Raspbian
